print("Hello World")
print("Ali")
print("Ali Hassan")
print("Hi, I am python")
print(25)
print(2*2)
print(2+5+9)
print("Hello,","I","am","Ali.")
print("Ali","is","20","years","old")
print(5,"+",4,"=",5+4)